### ISSUE TITLE
请问下，左滑删除有吗？

### ISSUE THREAD

**Issue by Everan-1994** [Aaron52077/wuli-ui#1]
如题！

**Comment by Aaron52077** [comment]
有的哦！ 请在单元格例子最后个例子查看哦！

**Comment by Everan-1994** [comment]
是不是代码没更新？单元格最后的例子，屏幕被我滑爆了都没动哦！

**Comment by Aaron52077** [comment]
对的，小程序demo还未审核通过，后期更新，不过源码里面有哦。请留意

**Comment by Aaron52077** [comment]
已更新了哦




| |
陈俊超
邮箱：chao_code520@163.com
|

签名由 网易邮箱大师 定制

在2018年05月13日 08:58，Everan 写道：

是不是代码没更新？单元格最后的例子，屏幕被我滑爆了都没动哦！

**Comment by Everan-1994** [comment]
你好，今天看了下左滑有了，说下使用后感，左滑的时候，会有滚动条往上滚了，然后问下，是否可以借鉴下微信聊天列表，滑动一个，滑第二个的时候，前面一个被滑动的，自动回滚。然后~~辛苦了！👍
