### ISSUE TITLE
意见与反馈1

### ISSUE THREAD

**Issue by eveinzz** [Aaron52077/wuli-ui#2]
### 亮点：
插件类，码类和悬浮按钮，键盘类，非常好。

### 缺点：
可移植性差，现在很多小程序都在使用成熟的团队维护的UI组件。比如我要用悬浮组件，然后我弄了一会发现，该UI库使用了自己的解析方法，导致我要用一个插件就增加了很多东西，而且我只用这一个组件增加的代码量竟然比自己写一个还要多得多多（components文件、index.js、component.js）。 最终虽然使用完成，但考虑可移植性差还是放弃使用。

### 建议：
像vant或有zanui或minui一样，做成移植性很好的组件形式，我要用哪个组件，直接调用设定值就行，不用改很多东西，这个改的东西是基于UI框架基础调用构成的。

**Comment by Aaron52077** [comment]
谢谢您的建议，其实当初理解的是需要哪个版块的加载哪个模块，不造成代码冗杂，没有做到大团队的全局加载部分引用哦！
